# frozen_string_literal: true

require "spec_helper"

RSpec.describe Sidenotes::Formatter do
  let(:model_name) { "User" }
  let(:data) do
    {
      "metadata" => { "table_name" => "users", "primary_key" => "id" },
      "columns" => [
        { "name" => "id", "type" => "integer", "nullable" => false },
        { "name" => "name", "type" => "string", "nullable" => false }
      ]
    }
  end

  describe "#render" do
    context "with YAML format" do
      before { Sidenotes.configure { |c| c.format = :yaml } }

      subject(:output) { described_class.new(model_name, data).render }

      it "produces valid YAML" do
        # Strip the comment header lines to parse
        yaml_content = output.lines.reject { |l| l.start_with?("#") }.join
        parsed = YAML.safe_load(yaml_content)
        expect(parsed).to be_a(Hash)
        expect(parsed).to have_key("User")
      end

      it "includes a header comment with version" do
        expect(output).to include("Generated by Sidenotes v#{Sidenotes::VERSION}")
      end

      it "includes a header comment with timestamp" do
        expect(output).to match(/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC/)
      end

      it "includes the model data" do
        yaml_content = output.lines.reject { |l| l.start_with?("#") }.join
        parsed = YAML.safe_load(yaml_content)
        expect(parsed["User"]["metadata"]["table_name"]).to eq("users")
      end

      it "includes column data" do
        yaml_content = output.lines.reject { |l| l.start_with?("#") }.join
        parsed = YAML.safe_load(yaml_content)
        columns = parsed["User"]["columns"]
        expect(columns.first["name"]).to eq("id")
      end

      it "starts with YAML document separator" do
        non_comment_lines = output.lines.reject { |l| l.start_with?("#") }
        expect(non_comment_lines.first.strip).to eq("---")
      end
    end

    context "with JSON format" do
      before { Sidenotes.configure { |c| c.format = :json } }

      subject(:output) { described_class.new(model_name, data).render }

      it "produces valid JSON" do
        parsed = JSON.parse(output)
        expect(parsed).to be_a(Hash)
      end

      it "includes generation metadata" do
        parsed = JSON.parse(output)
        expect(parsed["_generated_by"]).to include("Sidenotes")
        expect(parsed["_generated_at"]).to match(/\d{4}-\d{2}-\d{2}/)
      end

      it "includes the model data" do
        parsed = JSON.parse(output)
        expect(parsed["User"]["metadata"]["table_name"]).to eq("users")
      end
    end
  end
end
