# frozen_string_literal: true

require 'yaml'
require 'json'

module Sidenotes
  class Formatter
    HEADER_COMMENT = "# Generated by Sidenotes v%<version>s on %<timestamp>s\n" \
                     "# Do not edit manually — regenerate with `rake sidenotes:generate`\n"

    def initialize(model_name, data)
      @model_name = model_name
      @data = data
    end

    def render
      case Sidenotes.configuration.format
      when :yaml then render_yaml
      when :json then render_json
      end
    end

    private

    def render_yaml
      header = format(
        HEADER_COMMENT,
        version: Sidenotes::VERSION,
        timestamp: Time.now.utc.strftime('%Y-%m-%d %H:%M:%S UTC')
      )

      content = { @model_name => @data }
      yaml_output = YAML.dump(content)
      # Remove the leading "---\n" for cleaner output, we'll add the header instead
      yaml_output = yaml_output.sub(/\A---\n/, '')

      "#{header}---\n#{yaml_output}"
    end

    def render_json
      content = {
        '_generated_by' => "Sidenotes v#{Sidenotes::VERSION}",
        '_generated_at' => Time.now.utc.strftime('%Y-%m-%d %H:%M:%S UTC'),
        @model_name => @data
      }

      JSON.pretty_generate(content)
    end
  end
end
